export const LOAD_LATEST_MOVIES_SUCCESS     = 'LOAD_LATEST_MOVIES_SUCCESS';
export const LOAD_NOW_MOVIES_SUCCESS        = 'LOAD_NOW_MOVIES_SUCCESS';
export const LOAD_TOP_MOVIES_SUCCESS        = 'LOAD_TOP_MOVIES_SUCCESS';
export const LOAD_POPULAR_MOVIES_SUCCESS    = 'LOAD_POPULAR_MOVIES_SUCCESS';
export const LOAD_UPCOMING_MOVIES_SUCCESS   = 'LOAD_UPCOMING_MOVIES_SUCCESS';

export const LOAD_MOVIE_DETAILS_SUCCESS     = 'LOAD_MOVIE_DETAILS_SUCCESS';
export const SEARCH_MOVIE_SUCCESS           = 'SEARCH_MOVIE_SUCCESS';
export const LOAD_SIMILAR_SUCCESS           = 'LOAD_SIMILAR_SUCCESS';
